services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=product-service'
    ports:
      - '27017'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=inventory-service'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=order-service'
      - 'MYSQL_ROOT_PASSWORD=mysql'
      - 'MYSQL_ROOT_USER=root'
    ports:
      - '3307:3306'